name: Build

on: push
jobs:
  build_lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: "Install Dependencies"
      run: |
        sudo apt-get update && sudo apt-get install build-essential git libusb-1.0-0 libusb-1.0-0-dev libudev-dev
    - name: "Build Lib"
      run: |
        npm i
        npm run build